theme: jekyll-theme-architect

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/_posts'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}   
